### PR TITLE
fcbfd4e Can now pull to anywhere

### PR DESCRIPTION
**Pull request by svs**

### CODE REVIEW

**Comment by svs** [comment]
Hey, I added some functionality to your gem so you can pull to any arbitrary branch, even in the parent repo,

Please merge if you find the functionality useful. 

cheers
svs

**Comment by ghost** [comment]
Nice. :clap: As soon as I saw this I had the same ideas.

**Comment by svs** [comment]
still sorting out a few niggling bugs....it's really hard to test this functionality without messing with other people's repos ;-) !

**Comment by ghost** [comment]
Yea, I know what you mean, I will play around with it later today and see if I run into any problems.

**Comment by ghost** [comment]
I'm learning how to use pull request 8-)

**Comment by gabebw** [comment]
Hey, thanks, but this repository is no longer maintained. I use [hub](https://github.com/github/hub)'s `hub pull-request` tool now.

**Pull request closed without merging**
